<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UniversityCutOff;
use Illuminate\Support\Facades\DB;

class KyambogoUniversityCutOffsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data from: https://kyu.ac.ug/cut-off-point/
     * Academic Year: 2025/2026 - Private Sponsorship
     */
    public function run()
    {
        // Clear existing Kyambogo records for 2025
        UniversityCutOff::where('university_name', 'Kyambogo University')
            ->where('academic_year', 2025)
            ->delete();

        $programs = [
            ['Bachelor of Adult and Community Education - KyU(Day)', 'ACD', 16.1],
            ['Bachelor of Adult and Community Education - KyU(Evening)', 'ACE', 17.2],
            ['Bachelor of Art and Design with Education -Bushenyi (Day)', 'ADB', 21.4],
            ['Bachelor of Art and Design with Education - KyU (Day)', 'ADD', 22.6],
            ['Bachelor of Art and Design with Education - KyU (Evening)', 'ADE', 14.2],
            ['Bachelor of Art and Design with Education - KyU (Evening)', 'ADS', 13.4],
            ['Bachelor of Arts with Education - Bushenyi', 'AEB', 13.1],
            ['Bachelor of Arts with Education - KyU (Day)', 'AED', 30.8],
            ['Bachelor of Arts with Education - KyU (Evening)', 'AEE', 15.0],
            ['Bachelor of Arts with Education - Soroti (Day)', 'AES', 14.5],
            ['Bachelor of Science in Accounting and Finance - Bushenyi (Day)', 'AFB', 9.1],
            ['Bachelor of Science in Accounting and Finance - KyU (Day)', 'AFD', 29.8],
            ['Bachelor of Science in Accounting and Finance - KyU (Evening)', 'AFE', 22.4],
            ['Bachelor of Science in Accounting and Finance - Soroti (Day)', 'AFS', 9.2],
            ['Bachelor of Vocational Studies in Agriculture with Education- Bushenyi', 'AGB', 10.1],
            ['Bachelor of Vocational Studies in Agriculture with Education- KyU (Day)', 'AGD', 22.4],
            ['Bachelor of Vocational Studies in Agriculture with Education- KyU (Day)', 'AGE', 16.8],
            ['Bachelor of Vocational Studies in Agriculture with Education- Soroti', 'AGS', 10.6],
            ['Bachelor of Archeology and Heritage Studies - KyU (Day)', 'AHD', 18.0],
            ['Bachelor of Archeology and Heritage Studies - KyU (Evening)', 'AHE', 16.4],
            ['Bachelor of Art and Industrial Design - Bushenyi', 'AIB', 16.4],
            ['Bachelor of Art and Industrial Design - KyU (Day)', 'AID', 34.9],
            ['Bachelor of Art and Industrial Design - Soroti', 'AIS', 39.5],
            ['Bachelor of Engineering in Automotive and Power Engineering - KyU (Day)', 'APD', 43.4],
            ['Bachelor of Engineering in Automotive and Power Engineering - KyU (Evening)', 'APE', 40.2],
            ['Bachelor of Guidance and Counselling - Bushenyi', 'BCB', 11.8],
            ['Bachelor of Guidance and Counselling - KyU (Day)', 'BCD', 30.7],
            ['Bachelor of Guidance and Counselling - KyU (Evening)', 'BCE', 20.2],
            ['Bachelor of Guidance and Counselling - Soroti', 'BCS', 12.3],
            ['Bachelor of Civil and Building Engineering - KyU (Day)', 'BED', 46.9],
            ['Bachelor of Civil and Building Engineering - KyU (Evening)', 'BEE', 38.8],
            ['Bachelor of Science in Building Economics - Bushenyi', 'BGB', 7.9],
            ['Bachelor of Science in Building Economics - KyU (Day)', 'BGD', 32.1],
            ['Bachelor of Science in Building Economics - KyU (Evening)', 'BGE', 23.3],
            ['Bachelor of Science in Building Economics - Soroti', 'BGS', 8.5],
            ['Bachelor of Business Administration and Management - Bushenyi (Day)', 'BMB', 8.8],
            ['Bachelor of Business Administration and Management - KyU (Day)', 'BMD', 34.5],
            ['Bachelor of Business Administration and Management - KyU (Evening)', 'BME', 24.1],
            ['Bachelor of Business Administration and Management - Soroti (Day)', 'BMS', 10.1],
            ['Bachelor of Botany with Education - KyU (Day)', 'BOD', 28.2],
            ['Bachelor of Botany with Education - KyU (Evening)', 'BOE', 16.1],
            ['Bachelor of Engineering in Biosystems - KyU (Day)', 'BSD', 42.6],
            ['Bachelor of Engineering in Biosystems - KyU (Evening)', 'BSE', 35.7],
            ['Bachelor of Science in Chemistry with Education - Bushenyi', 'CHB', 12.8],
            ['Bachelor of Science in Chemistry with Education - KyU (Day)', 'CHD', 31.7],
            ['Bachelor of Science in Chemistry with Education - KyU (Evening)', 'CHE', 17.9],
            ['Bachelor of Science in Chemistry with Education - Soroti', 'CHS', 13.4],
            ['Bachelor of Engineering in Civil Engineering - KyU (Day)', 'CID', 46.8],
            ['Bachelor of Engineering in Civil Engineering - KyU (Evening)', 'CIE', 38.7],
            ['Bachelor of Commerce - Bushenyi (Day)', 'CMB', 8.4],
            ['Bachelor of Commerce - KyU (Day)', 'CMD', 32.1],
            ['Bachelor of Commerce - KyU (Evening)', 'CME', 23.2],
            ['Bachelor of Commerce - Soroti (Day)', 'CMS', 9.4],
            ['Bachelor of Procurement and Logistics Management - Bushenyi (Day)', 'CPB', 9.0],
            ['Bachelor of Procurement and Logistics Management - KyU (Day)', 'CPD', 28.5],
            ['Bachelor of Procurement and Logistics Management - KyU (Evening)', 'CPE', 21.4],
            ['Bachelor of Procurement and Logistics Management - Soroti (Day)', 'CPS', 10.4],
            ['Bachelor of Computer Science - Bushenyi (Day)', 'CSB', 9.6],
            ['Bachelor of Computer Science - KyU (Day)', 'CSD', 38.6],
            ['Bachelor of Computer Science - KyU (Evening)', 'CSE', 27.7],
            ['Bachelor of Computer Science - Soroti (Day)', 'CSS', 10.4],
            ['Bachelor of Vocational Studies in Construction with Education - Bushenyi', 'CTB', 8.7],
            ['Bachelor of Vocational Studies in Construction with Education - KyU (Day)', 'CTD', 23.7],
            ['Bachelor of Vocational Studies in Construction with Education - KyU (Evening)', 'CTE', 16.2],
            ['Bachelor of Vocational Studies in Construction with Education - Soroti', 'CTS', 9.5],
            ['Bachelor of Disability Studies and Rehabilitation- KyU (Day)', 'DRD', 17.8],
            ['Bachelor of Disability Studies and Rehabilitation- KyU (Evening)', 'DRE', 15.3],
            ['Bachelor of Science in Economics and Statistics - Bushenyi (Day)', 'ECB', 8.6],
            ['Bachelor of Science in Economics and Statistics - KyU (Day)', 'ECD', 30.4],
            ['Bachelor of Science in Economics and Statistics - KyU (Evening)', 'ECE', 22.3],
            ['Bachelor of Science in Economics and Statistics - Soroti (Day)', 'ECS', 9.5],
            ['Bachelor of Education in Educational Management - Bushenyi', 'EDB', 10.3],
            ['Bachelor of Education in Educational Management - KyU (Day)', 'EDD', 26.0],
            ['Bachelor of Education in Educational Management - KyU (Evening)', 'EDE', 17.4],
            ['Bachelor of Education in Educational Management - Soroti', 'EDS', 11.0],
            ['Bachelor of Early Childhood Education -Bushenyi', 'EEB', 10.8],
            ['Bachelor of Early Childhood Education - KyU (Day)', 'EED', 26.7],
            ['Bachelor of Early Childhood Education - KyU (Evening)', 'EEE', 17.8],
            ['Bachelor of Early Childhood Education - Soroti', 'EES', 11.6],
            ['Bachelor of Engineering in Electrical Engineering - KyU (Day)', 'ELD', 44.3],
            ['Bachelor of Engineering in Electrical Engineering - KyU (Evening)', 'ELE', 37.9],
            ['Bachelor of Science in Electrical Engineering Technology - Bushenyi', 'ETB', 9.3],
            ['Bachelor of Science in Electrical Engineering Technology - KyU (Day)', 'ETD', 35.8],
            ['Bachelor of Science in Electrical Engineering Technology - KyU (Evening)', 'ETE', 28.2],
            ['Bachelor of Science in Electrical Engineering Technology - Soroti', 'ETS', 10.0],
            ['Bachelor of Vocational Studies in Fashion Design with Education - Bushenyi', 'FDB', 8.6],
            ['Bachelor of Vocational Studies in Fashion Design with Education - KyU (Day)', 'FDD', 23.1],
            ['Bachelor of Vocational Studies in Fashion Design with Education - KyU (Evening)', 'FDE', 15.9],
            ['Bachelor of Vocational Studies in Fashion Design with Education - Soroti', 'FDS', 9.4],
            ['Bachelor of Fine Art - Bushenyi', 'FEB', 16.0],
            ['Bachelor of Fine Art - KyU (Day)', 'FED', 35.0],
            ['Bachelor of Fine Art - KyU (Evening)', 'FEE', 11.5],
            ['Bachelor of Fine Art - Soroti', 'FES', 36.8],
            ['Bachelor of Science in Food Science and Post-Harvest Technology - Bushenyi (Day)', 'FSB', 7.8],
            ['Bachelor of Science in Food Science and Post-Harvest Technology - KyU (Day)', 'FSD', 24.5],
            ['Bachelor of Science in Food Science and Post-Harvest Technology - KyU (Evening)', 'FSE', 18.6],
            ['Bachelor of Science in Food Science and Post-Harvest Technology - Soroti (Day)', 'FSS', 8.8],
            ['Bachelor of Geography with Education - Bushenyi', 'GEB', 12.1],
            ['Bachelor of Geography with Education - KyU (Day)', 'GED', 29.9],
            ['Bachelor of Geography with Education - KyU (Evening)', 'GEE', 16.8],
            ['Bachelor of Geography with Education - Soroti', 'GES', 12.8],
            ['Bachelor of Science in Information Systems - Bushenyi (Day)', 'INB', 9.1],
            ['Bachelor of Science in Information Systems - KyU (Day)', 'IND', 33.6],
            ['Bachelor of Science in Information Systems - KyU (Evening)', 'INE', 25.5],
            ['Bachelor of Science in Information Systems - Soroti (Day)', 'INS', 10.0],
            ['Bachelor of Science in Information Technology - Bushenyi (Day)', 'ITB', 9.1],
            ['Bachelor of Science in Information Technology - KyU (Day)', 'ITD', 35.2],
            ['Bachelor of Science in Information Technology - KyU (Evening)', 'ITE', 26.6],
            ['Bachelor of Science in Information Technology - Soroti (Day)', 'ITS', 10.0],
            ['Bachelor of Library and Information Science - KyU (Day)', 'LID', 28.5],
            ['Bachelor of Library and Information Science - KyU (Evening)', 'LIE', 16.5],
            ['Bachelor of Music, Dance and Drama - KyU (Day)', 'MDD', 26.7],
            ['Bachelor of Music, Dance and Drama - KyU (Evening)', 'MDE', 12.1],
            ['Bachelor of Engineering in Mechanical Engineering - KyU (Day)', 'MED', 44.3],
            ['Bachelor of Engineering in Mechanical Engineering - KyU (Evening)', 'MEE', 37.9],
            ['Bachelor of Science in Mathematics with Education - Bushenyi', 'MTB', 12.3],
            ['Bachelor of Science in Mathematics with Education - KyU (Day)', 'MTD', 31.1],
            ['Bachelor of Science in Mathematics with Education - KyU (Evening)', 'MTE', 17.4],
            ['Bachelor of Science in Mathematics with Education - Soroti', 'MTS', 13.1],
            ['Bachelor of Engineering in Mechatronics and Control Engineering - KyU (Day)', 'MXD', 42.9],
            ['Bachelor of Engineering in Mechatronics and Control Engineering - KyU (Evening)', 'MXE', 36.8],
            ['Bachelor of Science in Physics with Education - Bushenyi', 'PHB', 12.0],
            ['Bachelor of Science in Physics with Education - KyU (Day)', 'PHD', 30.5],
            ['Bachelor of Science in Physics with Education - KyU (Evening)', 'PHE', 17.2],
            ['Bachelor of Science in Physics with Education - Soroti', 'PHS', 12.8],
            ['Bachelor of Philosophy -KyU (Day)', 'PLD', 28.6],
            ['Bachelor of Philosophy -KyU (Evening)', 'PLE', 16.1],
            ['Bachelor of Population and Reproductive Health - KyU (Day)', 'PRD', 17.0],
            ['Bachelor of Population and Reproductive Health - KyU (Evening)', 'PRE', 14.7],
            ['Bachelor of Science Education - Bushenyi', 'SEB', 11.8],
            ['Bachelor of Science Education - KyU (Day)', 'SED', 28.8],
            ['Bachelor of Science Education - KyU (Evening)', 'SEE', 16.2],
            ['Bachelor of Science Education - Soroti', 'SES', 12.6],
            ['Bachelor of Social Work and Social Administration - Bushenyi (Day)', 'SWB', 9.4],
            ['Bachelor of Social Work and Social Administration - KyU (Day)', 'SWD', 30.1],
            ['Bachelor of Social Work and Social Administration - KyU (Evening)', 'SWE', 18.9],
            ['Bachelor of Social Work and Social Administration - Soroti (Day)', 'SWS', 10.2],
            ['Bachelor of Engineering in Telecommunication Engineering - KyU (Day)', 'TED', 43.6],
            ['Bachelor of Engineering in Telecommunication Engineering - KyU (Evening)', 'TEE', 37.3],
            ['Bachelor of Technical and Vocational Teacher Education - Bushenyi', 'TVB', 10.3],
            ['Bachelor of Technical and Vocational Teacher Education - KyU (Day)', 'TVD', 24.8],
            ['Bachelor of Technical and Vocational Teacher Education - KyU (Evening)', 'TVE', 16.9],
            ['Bachelor of Technical and Vocational Teacher Education - Soroti', 'TVS', 11.0],
            ['Bachelor of Industrial Art and Design (Wood and Metal) - Bushenyi', 'WDB', 11.4],
            ['Bachelor of Industrial Art and Design (Wood and Metal) - KyU (Day)', 'WDD', 28.3],
            ['Bachelor of Industrial Art and Design (Wood and Metal) - KyU (Evening)', 'WDE', 12.8],
            ['Bachelor of Industrial Art and Design (Wood and Metal) - Soroti', 'WDS', 12.2],
            ['Bachelor of Science in Zoology with Education - KyU (Day)', 'ZOD', 27.4],
            ['Bachelor of Science in Zoology with Education - KyU (Evening)', 'ZOE', 15.5],
        ];

        foreach ($programs as $program) {
            UniversityCutOff::create([
                'university_name' => 'Kyambogo University',
                'course_name' => $program[0],
                'course_code' => $program[1],
                'degree_type' => 'bachelor',
                'minimum_principal_passes' => 2,
                'cut_off_points' => $program[2],
                'academic_year' => 2025,
                'duration_years' => 3,
                'is_active' => true,
            ]);
        }

        $this->command->info('Successfully imported ' . count($programs) . ' Kyambogo University programs for 2025/2026!');
    }
}
