<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\UniversityCutOff;

class MakerereUniversityCutOffsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data from: https://www.mak.ac.ug/sites/default/files/2025-07/Cut-Off-Points-DIRECT_ENTRY-Private-Sponsorship-2025-2026.pdf
     * Academic Year: 2025/2026 - Private Sponsorship
     * 
     * Format: [Program Name, Male Cut-off, Female Cut-off, Min Principal Passes, Program Category (stem/other)]
     */
    public function run()
    {
        // Clear existing Makerere records for 2025
        UniversityCutOff::where('university_name', 'Makerere University')
            ->where('academic_year', 2025)
            ->delete();

        // Format: [Program Name, Code, General Points, Male Points, Female Points]
        $programs = [
            ['Bachelor of Science in Accounting (Evening)-MUSBS', 'ACSE', 14.9, null, null],
            ['Bachelor of Business Administration (Day) - Jinja -Mak', 'ADJ', 14.2, null, null],
            ['Bachelor of Business Administration (Day)-Mak', 'ADM', 39.6, null, null],
            ['Bachelor of Agribusiness Management (Day)', 'AGM', null, 43.3, null],
            ['Bachelor of Agribusiness Management (Day)', 'AGM', null, null, 35.1],
            ['Bachelor of Applied Biology (Day)', 'APB', 34.0, null, 36.3],
            ['Bachelor of Vocational Studies in Agriculture (Evening)', 'APE', null, null, null],
            ['Bachelor of Applied Psychology (Day)', 'APS', 42.8, null, null],
            ['Bachelor of Architecture (Evening)', 'ARE', 30.3, null, null],
            ['Bachelor of Architecture (Day)', 'ART', null, 49.1, 42.5],
            ['Bachelor of Arts (Mus) - Day - Jinja Mak', 'ARJ', null, null, null],
            ['Bachelor of Arts (Mus) - Day', 'ARS', 51.6, null, null],
            ['Bachelor of Arts (Hums) - (Evening)', 'ASE', 15, null, null],
            ['Bachelor of Arts (Social Sciences) (Day)', 'ASS', 16.5, null, null],
            ['Bachelor of Adult and Community Education (Day)', 'BAC', 23.9, null, null],
            ['Bachelor of Science in Agriculture (Day)', 'BAG', null, 31.3, 32.8],
            ['Bachelor of Animal Production Tech & Mgt (Day)', 'BAP', null, 31.9, 32.8],
            ['Bachelor of Business Administration (Evening)-MUSBS', 'BBA', 27.4, null, null],
            ['Bachelor of Science in Biomedical Engineering (Day)', 'BBE', 31.1, null, null],
            ['Bachelor of Business Administration (Day)-MUSBS', 'BBD', 26.4, null, null],
            ['Bachelor of Science in Civil Engineering (Day)', 'BCE', 26.8, null, null],
            ['Bachelor of Science in Biochemistry (Day)', 'BCH', null, 45.7, 42.6],
            ['Bachelor of Business Computing (Day) Day', 'BCI', 16.8, null, null],
            ['Bachelor of Science in Biomedical Engineering', 'BIO', null, 39.1, 36.1],
            ['Bachelor of Science in Biotechnology (Day)', 'BIT', null, 30.8, 33.2],
            ['Bachelor of Science in Conservation Biology (Day)', 'BCB', null, 19.2, 23.3],
            ['Bachelor of Science in Community Education (Day)', 'BCE', 17.4, null, null],
            ['Bachelor of Science in Computer Engineering (Day)', 'BCS', null, 47.7, 41.4],
            ['Bachelor of Science in Dental Laboratory Technology', 'BDT', null, 38.5, 38.2],
            ['Bachelor of Arts in Economics (Day)-MUSBS', 'BEC', 21.6, null, null],
            ['Bachelor of Early Childhood Care and Education', 'BEY', null, 35.8, 32.2],
            ['Bachelor of Science (Education) (Day)', 'BED', null, 23.4, 27.6],
            ['Bachelor of Entrepreneurship (Day)-MUSBS', 'BEN', 18.1, null, null],
            ['Bachelor of Science in Fisheries and Aquaculture (Day)', 'BFS', 32.8, null, null],
            ['Bachelor of Science in Food Sciences (Day)', 'BGS', null, null, 36.0],
            ['Bachelor of Science in Geo-informatics (Day)', 'BGI', null, null, null],
            ['Bachelor of Human Resource Mgt (Evening)-MUSBS', 'BHE', 23.6, null, null],
            ['BSc Tourism and Hospitality Mgt (Day)-Jinja Mak', 'BHJ', 14.4, null, null],
            ['Bachelor of Tourism and Hospitality Mgt (Day)-Mak', 'BHM', 36.6, null, null],
            ['Bachelor of Intl Bus & Technology (Evening)-Jinja - Mak', 'BIA', 15, null, null],
            ['Bachelor of Industrial Business (Day)-MUSBS', 'BIB', 23.9, null, null],
            ['Bachelor of Science in Industrial Chemistry (Day)', 'BIC', null, 38.4, 34.9],
            ['Bachelor of Industrial Art & Applied Design (Day)', 'BID', 38.1, null, null],
            ['Bachelor of Science in Information Management (Day)', 'BIM', 15.8, null, null],
            ['Bachelor of Intl Business & Technology (Day) Makerere (Ggb)', 'BIT', null, 29.1, 23.5],
            ['BSc in Tourism and Hospitality Mgt (Afternoon)-Jinja Mak', 'BJA', 13.1, null, null],
            ['Bachelor of Science in Computing (Jinja) Evening', 'BJB', 15.1, null, null],
            ['Bachelor of Library & Information Science (Day)', 'BLI', 16.1, null, null],
            ['Bachelor of Journalism & Communication (Evening)', 'BJE', 35.4, null, null],
            ['Bachelor of Law (Day) (Jinja - MUHAS) Evening', 'BJU', 17.5, null, null],
            ['Bachelor of Law (Day) - Jinja - MUHAS', 'BJL', 9.8, null, null],
            ['Bachelor of Science in Accounting Jinja - MUSBS', 'BJS', 13.4, null, null],
            ['Bachelor of Science (Sewerage)-MUSBS', 'BLG', 14.8, null, null],
            ['Bachelor of Library and Information Science (Evening)', 'BLE', null, 19.5, 21.4],
            ['Bachelor of Leisure, Events and Hotel Mgt (Day)-Jinja - MUHS', 'BLC', 13.6, null, null],
            ['Bachelor of Science in Laboratory Science (Evening)', 'BLS', 14.2, null, null],
            ['Bachelor of Science in Environmental Health Science (Day)', 'BLT', 34.7, null, null],
            ['Bachelor of Leisure, Events & Hotel Management (Day)', 'BLM', 15.6, null, null],
            ['Bachelor of Biomedical Laboratory Technology (Day)', 'BLT', null, 41.9, 38.2],
            ['Bachelor of Arts in Mass Communication (Day)', 'BMC', 52.1, null, null],
            ['Bachelor of Business Administration (Mbale)-MUSBS', 'BML', 13.3, null, null],
            ['Bachelor of Science in Mathematics (Day)', 'BMA', 17.8, null, null],
            ['Bachelor of Marketing (Day)', 'BMR', null, 44.3, 43.4],
            ['Bachelor of Marketing (Day)', 'BMS', 15.4, null, null],
            ['Bachelor of Science in Commerce (Evening)-MUSBS', 'BME', 14.4, null, null],
            ['Bachelor of Science (Evening) (Busitema - MUSBS)', 'BML', 11.5, null, null],
            ['Bachelor of Science in Procurement & Supply Chain Mgt (Day)', 'BMP', null, 39.1, 38.2],
            ['Bachelor of Science in Forestry', 'BCF', 14.3, null, null],
            ['Bachelor of Pharmacy (Day)', 'BPH', null, 35.7, 37.1],
            ['Bachelor of Office and Information Management (Evening)', 'BOI', null, 43.5, 39.9],
            ['Bachelor of Petroleum Geoscience and Production (Day)', 'BPG', 16.7, null, null],
            ['Bachelor of Land Economy (Day)', 'BLE', 19, null, null],
            ['Bachelor of Leisure, Events and Hotel Mgt (Evening)-MUHS', 'BLM', null, null, null],
            ['Bachelor of Pharmaceutical Laboratory Technology (Day)', 'BPT', null, 44.4, 47.4],
            ['Bachelor of Optometry (Day)', 'BOP', null, 40.2, 39.6],
            ['Bachelor of Science in Quantitative Economics (Day)', 'BOE', 13.3, null, null],
            ['Bachelor of Procurement & Supply Mgt (Evening)-MUSBS', 'BPE', 13.6, null, null],
            ['Bachelor of Science in Real Estate Mgt (Day)', 'BRM', 15.7, null, null],
            ['Bachelor of Real Estate Management (Evening)-Jinja - MUSBS', 'BRM', 12.7, null, null],
            ['Bachelor of Pharmacy (Evening)', 'BRP', 23.2, null, null],
            ['Bachelor of Science in Agribusiness (Day)', 'BSA', 27.7, null, null],
            ['Bachelor of Information Systems & Technology (Evening)-Mak', 'BSF', 15.3, null, null],
            ['Bachelor of Software Engineering Technology (Day)', 'BSE', 31.8, null, null],
            ['Bachelor of Statistics (Day)', 'BST', null, 40.5, 37.9],
            ['Bachelor of Business Statistics (Evening)-MUSBS', 'BST', 9.2, null, null],
            ['Bachelor of Public Administration (Evening)-Mak', 'BSV', 15.3, null, null],
            ['Bachelor of Science in Public Administration (Day)', 'BPA', null, 44.7, 40.2],
            ['Bachelor of International Business (Evening)', 'BTB', 17, null, null],
            ['Bachelor of Tourism and Tourism and Hospitality Mgt (Evening)', 'BTE', 31.8, null, null],
            ['Bachelor of Science in Tourism & Hospitality Mgt - MUSBS', 'BTH', 15.4, null, null],
            ['Bachelor of Urban & Regional Planning (Day)', 'BUP', 36.2, null, null],
            ['Bachelor of Statistics (Day)-MUSBS', 'BUS', 10.2, null, null],
            ['Bachelor of Science in Social Work & Social Admin', 'BSW', 31.2, null, null],
            ['Bachelor of Science in Valuation', 'BVA', null, 38.4, 37.8],
            ['Bachelor of Environmental Sciences (Day)', 'BVE', null, 32.8, 35.5],
            ['Bachelor of Veterinary Medicine (Day)', 'BVM', null, 43.8, 38.9],
            ['Bachelor of Cytotechnology (Day)', 'BVT', null, 37.9, null],
            ['Bachelor of Science (Westlands Manor) (Evening)', 'BWW', 14.6, null, null],
            ['Bachelor of Construction Management & Engineering (Day)', 'CEM', null, 34.6, 23.5],
            ['Bachelor of Commerce (Afternoon)', 'CEA', 32.6, null, null],
            ['Bachelor of Civil and Environmental Engineering-Mak', 'CEV', null, 47.7, 45.9],
            ['Bachelor of Commerce (Afternoon)-MUSBS', 'CMA', 11.9, null, null],
            ['Bachelor of Commerce (Evening)-MUSBS', 'CME', 11.5, null, null],
            ['Bachelor of Commerce (Day)-Makerere', 'CMK', 37.3, null, null],
            ['Bachelor of Commerce (Day)-Mak', 'COM', 19.6, null, null],
            ['Bachelor of Commerce (Day)-MUSBS', 'COM', 19.6, null, null],
            ['Bachelor of Procurement & Supply Chain Mgt (Day)-Jinja - MUSBS', 'CPJ', 14.9, null, null],
            ['Bachelor of Procurement & Supply Chain Mgt (Evening)-Jinja - MUSBS', 'CPE', 13.1, null, null],
            ['Bachelor of Science in Computer Science (Day)', 'CSC', null, 38, 43.1],
            ['BSc in Comp Engr & Information Tech (Evening)-Mak', 'CSE', null, 39.1, 41.1],
            ['Bachelor of Computer Science (Day)-Jinja Mak', 'CSJ', null, 28.7, null],
            ['Bachelor of Commercial (Evening)-Jinja Mak', 'CXJ', null, null, null],
            ['Bachelor of Arts (Performing Arts) (Day)', 'DPA', 16.3, null, null],
            ['Bachelor of Development Studies (Day)', 'DPS', 31.7, null, null],
            ['Bachelor of Arts in Economics (Jinja - Mak) Day', 'ECJ', 9.1, null, null],
            ['Bachelor of Science in Economics (Evening)-Mak', 'ECN', null, null, null],
            ['Bachelor of Arts in Education (Day)-Mak', 'EDA', 34.1, null, null],
            ['Bachelor of Arts with Education (Day)', 'EDA', 34.3, null, null],
            ['Bachelor of Science with Education (Afternoon) Day', 'EDB', null, 41.5, 35],
            ['Bachelor of Science with Education (Evening)', 'EDE', null, 23.4, 28.6],
            ['Bachelor of Science with Education (Economics) Day', 'EEC', null, 30.9, 30.2],
            ['Bachelor of Science in Electrical Engineering (Day)', 'ELE', null, 48.9, 43.8],
            ['Bachelor of Science in Electronics Engineering (Day)', 'ELT', null, 44.6, 40.0],
            ['Bachelor of Human Resource Mgt (Evening)-Mbale-MUSBS', 'HBA', 15, null, null],
            ['Bachelor of Human Resource Mgt (Day)-Fortportal - Mak', 'HRA', 19.7, null, null],
            ['Bachelor of Human Resource Mgt (Afternoon)-MUSBS', 'HRM', 16.2, null, null],
            ['Bachelor of Human Resource Mgt (Eve) Makerere - MUSBS', 'HOM', 22.7, null, null],
            ['Bachelor of Science in Industrial Art (Day)-Jinja - MUSBS', 'HSJ', 13.6, null, null],
            ['Bachelor of Industrial & Organizational Psychology (Day)', 'IOP', 42.1, null, null],
            ['Bachelor of Information Sys and Technology', 'IIT', 36.9, null, null],
            ['Bachelor of Science Administration (Afternoon)-Jinja - Mak', 'JAN', 15, null, null],
            ['Bachelor of Journalism & Communication (Day)', 'JMC', null, 19.7, 19.7],
            ['Bachelor of Entrepreneurship (Evening)-Jinja', 'JBE', null, null, null],
            ['Bachelor of Commerce (Afternoon)-Jinja - Mak', 'JCA', null, null, null],
            ['Bachelor of Commerce (Afternoon)-Jinja Mak', 'JCM', 12, null, null],
            ['Bachelor of Commerce (Afternoon)-Jinja Mak', 'JOM', null, null, null],
            ['Bachelor of Law (Day)-Makerere', 'LAW', 14.2, null, null],
            ['Bachelor of Library and Information Science (Day)', 'LIS', 27.2, null, null],
            ['BSc - Law (Social Work & Soc Servs Admin) (Day)', 'LSD', null, 9, 43.7],
            ['Bachelor of Science in Land Management (Day)', 'LMG', null, 49.1, 40.7],
            ['Bachelor of Science in Mechanical Engineering (Day)', 'MEC', null, 47.9, 43],
            ['Bachelor of Science in Laboratory Science (Day)', 'MLT', null, 41.9, 49.4],
            ['Bachelor of Music (Day)', 'MUS', null, null, null],
            ['Bachelor of Nursing Science (Day)', 'NUR', null, 44.7, 43.3],
            ['Bachelor of Petroleum Chemistry (Day)', 'PAN', null, 49.9, 43.9],
            ['Bachelor of Petroleum Engineering (Day)', 'PEG', 19.6, null, null],
            ['Bachelor of Procurement & Supply Chain Mgt (Evening)-Mbale-MUSBS', 'PME', 13.3, null, null],
            ['Bachelor of Procurement & Supply Chain Mgt (Day)-Mbale-MUSBS', 'PML', 13.5, null, null],
            ['Bachelor of Procurement and Supply Chain Mgt (Day)-Mbale-MUSBS', 'PRB', 12.2, null, null],
            ['Bachelor of Procurement & Supply Chain Mgt (Evening)-MUSBS', 'PRE', 13.3, null, null],
            ['Bachelor of Procurement and Supply Chain Mgt (Evening)-MUSBS', 'PRM', 18.3, null, null],
            ['Bachelor of Procurement and Supply Chain Mgt (Day) (Fort Portal-MUSBS)', 'PRM', 20.8, null, null],
            ['Bachelor of Science in Food Science & Technology (Day)', 'FST', 15.6, null, null],
            ['Bachelor of Science in Industrial Science (Day)', 'SAS', null, 25.3, 25.3],
            ['Bachelor of Science (Musgrail) (Day)', 'SCB', null, 20.9, 28.5],
            ['Bachelor of Science (Economics) (Day)', 'SCE', null, 45.4, 40.0],
            ['Bachelor of Science (Extension)', 'SCX', 20.2, null, 22.1],
            ['Bachelor of Science (Evening)', 'SCS', 15.9, null, 17.3],
            ['Bachelor of Science (Day) (Busitema)', 'SCB', 13.2, null, 16.3],
            ['Bachelor of Science in Quantity Surveying (Day)', 'SQS', 44.8, null, 42.1],
            ['Bachelor of Surveying (Evening)', 'SRE', 43.6, null, 39.8],
            ['Bachelor of Science in Surveying (Day)', 'SRV', null, null, 41.9],
            ['Bachelor of Statistics (Day)', 'STA', 29.7, null, 28.7],
            ['Bachelor of Science & Egr Mgt (Day)-MUSBS', 'STM', 11.6, null, null],
            ['Bachelor of Telecommunications Engr (Day)', 'TLM', 37.3, null, null],
            ['Bachelor of Veterinary Medicine (Day)', 'VET', 43.6, null, null],
            ['Bachelor of Zoology (Day)', 'ZOO', 52.0, null, null],
            ['Bachelor of Science in Zoology', 'ZLG', 32.0, null, null],
        ];

        foreach ($programs as $program) {
            // Skip if all cut-off points are null
            if ($program[2] === null && $program[3] === null && $program[4] === null) {
                continue;
            }
            
            UniversityCutOff::create([
                'university_name' => 'Makerere University',
                'course_name' => $program[0],
                'course_code' => $program[1],
                'cut_off_points' => $program[2],
                'cut_off_points_male' => $program[3],
                'cut_off_points_female' => $program[4],
                'minimum_principal_passes' => 2,
                'program_category' => ($program[3] !== null || $program[4] !== null) ? 'stem' : 'other',
                'degree_type' => 'bachelor',
                'academic_year' => 2025,
                'duration_years' => 3,
                'is_active' => true,
            ]);
        }

        $this->command->info('Successfully imported ' . count($programs) . ' Makerere University programs for 2025/2026!');
    }
}
